# Generated by Django 2.1.7 on 2019-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190720_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dttm_created',
        ),
        migrations.AlterField(
            model_name='item',
            name='dttm_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
